package kitty

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// PinSessionFiles maps shortcut slots to generated Kitty session files.
type PinSessionFiles map[string]string

// PinShortcutsContent renders all ten mappings so removed pins explicitly
// clear their previous Kitty configuration.
func PinShortcutsContent(pins PinSessionFiles) []byte {
	var content strings.Builder
	content.WriteString("# Generated by kesh. Changes will be overwritten.\n")
	for slot := 0; slot <= 9; slot++ {
		key := strconv.Itoa(slot)
		file := pins[key]
		if file == "" {
			fmt.Fprintf(&content, "map cmd+%s\n", key)
			continue
		}
		fmt.Fprintf(&content, "map cmd+%s goto_session %s\n", key, strconv.Quote(file))
	}
	return []byte(content.String())
}

// SavePinShortcuts atomically writes the generated Kitty mapping file.
func SavePinShortcuts(path string, pins PinSessionFiles) (bool, error) {
	content := PinShortcutsContent(pins)
	if current, err := os.ReadFile(path); err == nil && string(current) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read Kitty pin shortcuts: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return false, fmt.Errorf("create Kitty shortcut directory: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".kitty-pins-*.conf")
	if err != nil {
		return false, fmt.Errorf("create Kitty pin shortcuts: %w", err)
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return false, err
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return false, err
	}
	if err := temporary.Close(); err != nil {
		return false, err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return false, fmt.Errorf("save Kitty pin shortcuts: %w", err)
	}
	return true, nil
}

// SyncPinShortcuts writes mappings and reloads Kitty only when they changed.
func (c Client) SyncPinShortcuts(path string, pins PinSessionFiles) error {
	changed, err := SavePinShortcuts(path, pins)
	if err != nil || !changed {
		return err
	}
	return c.LoadConfig()
}
