package config

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	ProjectFileName = ".kesh.yaml"
)

var unsafeEnvNameChars = regexp.MustCompile(`[^A-Za-z0-9]+`)

type Config struct {
	Worktree   WorktreeConfig `yaml:"worktree"`
	Workspaces []Workspace    `yaml:"workspaces"`
}

type WorktreeConfig struct {
	Dir      string   `yaml:"dir"`
	Defaults Defaults `yaml:"defaults"`
}

type Defaults struct {
	Files Files `yaml:"files"`
}

type Workspace struct {
	Name  string        `yaml:"name"`
	Repo  string        `yaml:"repo"`
	Panes []PaneCommand `yaml:"panes"`
	// Commands is a legacy alias for Panes.
	Commands []PaneCommand `yaml:"commands"`
	Worktree Worktree      `yaml:"worktree"`
}

type Worktree struct {
	Files          Files           `yaml:"files"`
	Hooks          Hooks           `yaml:"hooks"`
	RandomizePorts []RandomizePort `yaml:"randomize_ports"`
	SetEnv         []SetEnv        `yaml:"set_env"`
}

type RandomizePort struct {
	File string   `yaml:"file"`
	Vars []string `yaml:"vars"`
}

type SetEnv struct {
	File string            `yaml:"file"`
	Vars map[string]string `yaml:"vars"`
}

type PaneCommand struct {
	Commands   []string `yaml:"commands"`
	Split      string   `yaml:"split"`
	Focus      bool     `yaml:"focus"`
	Zoom       bool     `yaml:"zoom"`
	Size       string   `yaml:"size"`
	Percentage int      `yaml:"percentage"`
}

type Files struct {
	Copy    []string `yaml:"copy"`
	Symlink []string `yaml:"symlink"`
}

type Hooks struct {
	PostCreate []string `yaml:"post_create"`
}

func ProjectPath(projectDir string) string {
	return filepath.Join(projectDir, ProjectFileName)
}

func ProjectTemplate() string {
	return `# kesh project config
# Generated by kesh init.
# Cleanup needs no config.

# worktree:
#   dir: ~/workspace/worktrees
#   defaults:
#     files:
#       copy:
#         - .env
#       symlink:
#         - AGENTS.override.md
workspaces:
  - name: window_name
    repo: .
    # worktree:
    #   files:
    #     copy:
    #       - .env.local
    #     symlink:
    #       - .tool-versions
    #   hooks:
    #     post_create:
    #       - pnpm install
    #   randomize_ports:
    #     - file: .env.local
    #       vars:
    #         - PORT
    #         - APP_PORT
    #   set_env:
    #     - file: .env.local
    #       vars:
    #         API_URL: "http://localhost:${window_name:.env.local:PORT}"
    # panes:
    #   - commands:
    #       - nvim
    #     focus: true
    #   - split: horizontal # omit commands to open an interactive shell
    #   - commands:
    #       - pnpm install
    #       - pnpm run dev
    #     split: horizontal
    #   - commands:
    #       - kesh-agent
    #     split: vertical # splits the immediately preceding pane

`
}

func WriteProjectTemplate(projectDir string) (string, error) {
	configPath := ProjectPath(projectDir)
	file, err := os.OpenFile(configPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if os.IsExist(err) {
			return "", fmt.Errorf("config already exists: %s", configPath)
		}
		return "", err
	}
	_, writeErr := file.WriteString(ProjectTemplate())
	closeErr := file.Close()
	if writeErr != nil {
		return "", writeErr
	}
	if closeErr != nil {
		return "", closeErr
	}
	return configPath, nil
}

func FindProjectPath(startDir string, repoRoot string) (string, bool, error) {
	current, err := filepath.Abs(startDir)
	if err != nil {
		return "", false, err
	}
	current = filepath.Clean(current)
	root, err := filepath.Abs(repoRoot)
	if err != nil {
		return "", false, err
	}
	root = filepath.Clean(root)
	insideRoot, err := pathIsWithinRoot(current, root)
	if err != nil {
		return "", false, err
	}
	if !insideRoot {
		return "", false, fmt.Errorf("start directory must be inside git repo root: %s", startDir)
	}

	for {
		configPath := ProjectPath(current)
		if _, err := os.Stat(configPath); err == nil {
			return configPath, true, nil
		} else if !os.IsNotExist(err) {
			return "", false, err
		}
		atRoot, err := sameFile(current, root)
		if err != nil {
			return "", false, err
		}
		if atRoot {
			return ProjectPath(root), false, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return ProjectPath(root), false, nil
		}
		current = parent
	}
}

func pathIsWithinRoot(path string, root string) (bool, error) {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return false, err
	}
	if relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)) && !filepath.IsAbs(relative) {
		return true, nil
	}

	for current := path; ; current = filepath.Dir(current) {
		matches, err := sameFile(current, root)
		if err != nil {
			return false, err
		}
		if matches {
			return true, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return false, nil
		}
	}
}

func sameFile(left string, right string) (bool, error) {
	leftInfo, err := os.Stat(left)
	if err != nil {
		return false, err
	}
	rightInfo, err := os.Stat(right)
	if err != nil {
		return false, err
	}
	return os.SameFile(leftInfo, rightInfo), nil
}

func LoadProject(repoRoot string, homeDir string) (Config, error) {
	return LoadProjectFile(ProjectPath(repoRoot), homeDir)
}

func LoadProjectFile(configPath string, homeDir string) (Config, error) {
	projectConfig, err := LoadFile(configPath, homeDir)
	if err != nil {
		return Config{}, err
	}
	return projectConfig, nil
}

func LoadFile(filePath string, homeDir string) (Config, error) {
	stat, err := os.Stat(filePath)
	if os.IsNotExist(err) {
		return Config{}, nil
	}
	if err != nil {
		return Config{}, err
	}
	if !stat.Mode().IsRegular() {
		return Config{}, fmt.Errorf("config path is not a file: %s", filePath)
	}

	source, err := os.ReadFile(filePath)
	if err != nil {
		return Config{}, err
	}
	if len(bytes.TrimSpace(source)) == 0 {
		return Config{}, nil
	}

	var node yaml.Node
	if err := yaml.Unmarshal(source, &node); err != nil {
		return Config{}, fmt.Errorf("invalid YAML in %s: %w", filePath, err)
	}
	if err := validateNode(&node, filePath); err != nil {
		return Config{}, err
	}

	var config Config
	decoder := yaml.NewDecoder(bytes.NewReader(source))
	decoder.KnownFields(true)
	if err := decoder.Decode(&config); err != nil {
		return Config{}, fmt.Errorf("invalid config in %s: %w", filePath, err)
	}
	if err := validateConfig(&config, filePath, homeDir); err != nil {
		return Config{}, err
	}
	return config, nil
}

func (config Config) HasSetup() bool {
	if hasFiles(config.Worktree.Defaults.Files) {
		return true
	}
	for _, workspace := range config.Workspaces {
		if hasFiles(workspace.Worktree.Files) || hasHooks(workspace.Worktree.Hooks) || len(workspace.Worktree.RandomizePorts) > 0 || len(workspace.Worktree.SetEnv) > 0 {
			return true
		}
	}
	return false
}

func WorkspaceFiles(config Config, workspace Workspace) Files {
	defaults := configDefaultsFiles(config)
	return Files{
		Copy:    append(append([]string(nil), defaults.Copy...), workspace.Worktree.Files.Copy...),
		Symlink: append(append([]string(nil), defaults.Symlink...), workspace.Worktree.Files.Symlink...),
	}
}

func WorkspaceHooks(_ Config, workspace Workspace) Hooks {
	return Hooks{PostCreate: append([]string(nil), workspace.Worktree.Hooks.PostCreate...)}
}

func WorkspacePanes(workspace Workspace) []PaneCommand {
	if len(workspace.Panes) > 0 {
		return workspace.Panes
	}
	return workspace.Commands
}

func validateConfig(config *Config, filePath string, homeDir string) error {
	if config.Worktree.Dir != "" {
		if _, err := expandPath(config.Worktree.Dir, homeDir, filepath.Dir(filePath)); err != nil {
			return fmt.Errorf("invalid config in %s: worktree.dir %w", filePath, err)
		}
	}
	if err := validateFiles(config.Worktree.Defaults.Files, "worktree.defaults.files", filePath); err != nil {
		return err
	}

	names := map[string]bool{}
	envKeys := map[string]string{}
	for index, workspace := range config.Workspaces {
		prefix := fmt.Sprintf("workspaces[%d]", index)
		if strings.TrimSpace(workspace.Name) == "" {
			return fmt.Errorf("invalid config in %s: %s.name must be a non-empty string", filePath, prefix)
		}
		if names[workspace.Name] {
			return fmt.Errorf("invalid config in %s: duplicate workspace name %q", filePath, workspace.Name)
		}
		names[workspace.Name] = true
		envKey, err := WorkspaceDirEnvKey(workspace.Name)
		if err != nil {
			return fmt.Errorf("invalid config in %s: %s.name %w", filePath, prefix, err)
		}
		if previous, ok := envKeys[envKey]; ok {
			return fmt.Errorf("invalid config in %s: workspace env var %s conflicts between %q and %q", filePath, envKey, previous, workspace.Name)
		}
		envKeys[envKey] = workspace.Name
		if workspace.Repo != "" {
			if _, err := expandPath(workspace.Repo, homeDir, filepath.Dir(filePath)); err != nil {
				return fmt.Errorf("invalid config in %s: %s.repo %w", filePath, prefix, err)
			}
		}
		if err := validateFiles(workspace.Worktree.Files, prefix+".worktree.files", filePath); err != nil {
			return err
		}
		if err := validateStrings(workspace.Worktree.Hooks.PostCreate, prefix+".worktree.hooks.post_create", filePath); err != nil {
			return err
		}
		if err := validateRandomizePorts(workspace.Worktree.RandomizePorts, prefix+".worktree.randomize_ports", filePath); err != nil {
			return err
		}
		if err := validateSetEnv(workspace.Worktree.SetEnv, prefix+".worktree.set_env", filePath); err != nil {
			return err
		}
		if len(workspace.Panes) > 0 && len(workspace.Commands) > 0 {
			return fmt.Errorf("invalid config in %s: %s must use panes or commands, not both", filePath, prefix)
		}
		paneLabel := prefix + ".panes"
		if len(workspace.Commands) > 0 {
			paneLabel = prefix + ".commands"
		}
		for paneIndex, pane := range WorkspacePanes(workspace) {
			label := fmt.Sprintf("%s[%d]", paneLabel, paneIndex)
			if err := validatePaneCommand(pane, label, filePath); err != nil {
				return err
			}
			if pane.Zoom {
				return fmt.Errorf("invalid config in %s: %s.zoom is not supported by Kitty", filePath, label)
			}
			if pane.Size != "" {
				return fmt.Errorf("invalid config in %s: %s.size is not supported by Kitty; use percentage", filePath, label)
			}
		}
	}
	return nil
}

func WorkspaceDirEnvKey(workspaceName string) (string, error) {
	name := unsafeEnvNameChars.ReplaceAllString(strings.ToUpper(workspaceName), "_")
	name = strings.Trim(name, "_")
	if name == "" {
		return "", fmt.Errorf("must contain at least one letter or digit for its .kesh.env variable")
	}
	return "KESH_" + name + "_DIR", nil
}

func validatePaneCommand(command PaneCommand, label string, filePath string) error {
	if err := validateStrings(command.Commands, label+".commands", filePath); err != nil {
		return err
	}
	if command.Split != "" && command.Split != "horizontal" && command.Split != "vertical" {
		return fmt.Errorf("invalid config in %s: %s.split must be \"horizontal\" or \"vertical\"", filePath, label)
	}
	if command.Percentage < 0 || command.Percentage > 100 {
		return fmt.Errorf("invalid config in %s: %s.percentage must be between 1 and 100", filePath, label)
	}
	return nil
}

func validateFiles(files Files, label string, filePath string) error {
	if err := validateSetupPaths(files.Copy, label+".copy", filePath); err != nil {
		return err
	}
	return validateSetupPaths(files.Symlink, label+".symlink", filePath)
}

func validateRandomizePorts(randomizePorts []RandomizePort, key string, filePath string) error {
	for index, item := range randomizePorts {
		label := fmt.Sprintf("%s[%d]", key, index)
		if strings.TrimSpace(item.File) == "" {
			return fmt.Errorf("invalid config in %s: %s.file must be a non-empty string", filePath, label)
		}
		if err := validateSetupPaths([]string{item.File}, label+".file", filePath); err != nil {
			return err
		}
		if len(item.Vars) == 0 {
			return fmt.Errorf("invalid config in %s: %s.vars must define at least one variable", filePath, label)
		}
		seen := map[string]bool{}
		for varIndex, name := range item.Vars {
			varLabel := fmt.Sprintf("%s.vars[%d]", label, varIndex)
			if !isEnvVarName(name) {
				return fmt.Errorf("invalid config in %s: %s must be a valid env var name", filePath, varLabel)
			}
			if seen[name] {
				return fmt.Errorf("invalid config in %s: duplicate randomize port var %q in %s", filePath, name, label)
			}
			seen[name] = true
		}
	}
	return nil
}

func validateSetEnv(setEnv []SetEnv, key string, filePath string) error {
	for index, item := range setEnv {
		label := fmt.Sprintf("%s[%d]", key, index)
		if strings.TrimSpace(item.File) == "" {
			return fmt.Errorf("invalid config in %s: %s.file must be a non-empty string", filePath, label)
		}
		if err := validateSetupPaths([]string{item.File}, label+".file", filePath); err != nil {
			return err
		}
		if len(item.Vars) == 0 {
			return fmt.Errorf("invalid config in %s: %s.vars must define at least one variable", filePath, label)
		}
		for name := range item.Vars {
			if !isEnvVarName(name) {
				return fmt.Errorf("invalid config in %s: %s.vars key %q must be a valid env var name", filePath, label, name)
			}
		}
	}
	return nil
}

func isEnvVarName(value string) bool {
	if value == "" {
		return false
	}
	for index, char := range value {
		if index == 0 {
			if (char < 'A' || char > 'Z') && (char < 'a' || char > 'z') && char != '_' {
				return false
			}
			continue
		}
		if (char < 'A' || char > 'Z') && (char < 'a' || char > 'z') && (char < '0' || char > '9') && char != '_' {
			return false
		}
	}
	return true
}

func validateSetupPaths(values []string, key string, filePath string) error {
	if err := validateStrings(values, key, filePath); err != nil {
		return err
	}
	for index, value := range values {
		if filepath.IsAbs(value) {
			return fmt.Errorf("invalid config in %s: %s[%d] must be a relative file path", filePath, key, index)
		}
		if strings.ContainsRune(value, '\x00') {
			return fmt.Errorf("invalid config in %s: %s[%d] cannot contain null bytes", filePath, key, index)
		}
		for _, segment := range strings.FieldsFunc(value, func(r rune) bool { return r == '/' || r == '\\' }) {
			if segment == ".." {
				return fmt.Errorf("invalid config in %s: %s[%d] cannot contain \"..\"", filePath, key, index)
			}
		}
	}
	return nil
}

func validateStrings(values []string, key string, filePath string) error {
	for index, value := range values {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("invalid config in %s: %s[%d] must be a non-empty string", filePath, key, index)
		}
	}
	return nil
}

func validateNode(node *yaml.Node, filePath string) error {
	if node.Kind == yaml.DocumentNode && len(node.Content) == 1 {
		node = node.Content[0]
	}
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: expected an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "worktree", "workspaces":
			if key == "worktree" {
				if err := validateWorktreeNode(node.Content[i+1], filePath); err != nil {
					return err
				}
			}
		case "copy", "symlink", "postSetup", "windows", "mode":
			return fmt.Errorf("invalid config in %s: legacy key %q is not supported", filePath, key)
		default:
			return fmt.Errorf("invalid config in %s: unsupported key %q", filePath, key)
		}
	}
	return nil
}

func validateWorktreeNode(node *yaml.Node, filePath string) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: worktree must be an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "dir":
		case "defaults":
			if err := validateDefaultsNode(node.Content[i+1], filePath); err != nil {
				return err
			}
		default:
			return fmt.Errorf("invalid config in %s: unsupported worktree key %q", filePath, key)
		}
	}
	return nil
}

func validateDefaultsNode(node *yaml.Node, filePath string) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("invalid config in %s: defaults must be an object", filePath)
	}
	for i := 0; i < len(node.Content); i += 2 {
		key := node.Content[i].Value
		switch key {
		case "files":
		case "hooks":
			return fmt.Errorf("invalid config in %s: worktree.defaults.hooks is not supported; use workspaces[].worktree.hooks", filePath)
		default:
			return fmt.Errorf("invalid config in %s: unsupported defaults key %q", filePath, key)
		}
	}
	return nil
}

func ExpandConfiguredPath(value string, homeDir string, baseDir string) (string, error) {
	return expandPath(value, homeDir, baseDir)
}

func configDefaultsFiles(config Config) Files {
	return config.Worktree.Defaults.Files
}

func expandPath(value string, homeDir string, baseDir string) (string, error) {
	expanded := strings.TrimSpace(value)
	if strings.ContainsRune(expanded, '\x00') {
		return "", fmt.Errorf("cannot contain null bytes")
	}
	if expanded == "" {
		return "", fmt.Errorf("must be a non-empty path")
	}
	if expanded == "~" {
		expanded = homeDir
	} else if strings.HasPrefix(expanded, "~/") {
		expanded = filepath.Join(homeDir, expanded[2:])
	}
	if !filepath.IsAbs(expanded) {
		expanded = filepath.Join(baseDir, expanded)
	}
	return filepath.Abs(expanded)
}

func hasFiles(files Files) bool {
	return len(files.Copy) > 0 || len(files.Symlink) > 0
}

func hasHooks(hooks Hooks) bool {
	return len(hooks.PostCreate) > 0
}
